### ISSUE TITLE
dependancy suggestion

### ISSUE THREAD

**Issue by oshanz** [daniellockyer/pushmore-rust-client#3]
Hi, I'm trying to reduce build time of my app. and I've seen that this client use reqwest which has many mandatory dependencies. It seems this client doesn't need that much features. could you please consider some lightweight alternative. like https://crates.io/crates/minreq, https://crates.io/crates/ureq. thanks.

**Comment by daniellockyer** [comment]
Hey @oshanz! 👋🏻 Apologies for the delay, I didn't get a notification. For sure, I'll look into this and see what I can do 🙂

**Comment by daniellockyer** [comment]
Sorry, I forgot to tag the issue in the commit. This was fixed in https://github.com/daniellockyer/pushmore-rust-client/commit/909eebaec407ff9fbcb41090c95ae75d42d914ff 🙂
